installCRDs: true
keepCRDs: true
crds:
  install: true

controller:
  enabled: true
  replicas: 2

rbac:
  create: true
  clusterRole: true

dashboard:
  enabled: true
  extraArgs:
    - --root-path=/rollouts          # 명시적으로 슬래시 포함 권장
    - --namespace=default

  service:
    type: ClusterIP
    port: 3100

  # ✅ 차트 내 Ingress 비활성화 (충돌 원천 제거)
  ingress:
    enabled: false

