installCRDs: true
keepCRDs: true
crds:
  install: true

controller:
  enabled: true
  replicas: 2

rbac:
  create: true
  clusterRole: true

dashboard:
  enabled: true
  # 대시보드 기본 루트는 "rollouts" 입니다. (루트(/)로 바꾸지 않습니다)
  extraArgs:
    - --root-path=rollouts
    - --namespace=default

  service:
    type: ClusterIP
    port: 3100

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      # HTTP로 서비스 (80)
      traefik.ingress.kubernetes.io/router.entrypoints: web
      # TLS 사용 안 함 → 아래 tls 섹션 제거, router.tls 주석/삭제
      # traefik.ingress.kubernetes.io/router.tls: "false"
    hosts:
      - argorollouts.dokjongban.com
    # 유지보수 단순화: 하나의 Ingress에 정적(/rollouts) + API(/api) 동시 매핑
    paths:
      - /rollouts
      - /api
    pathType: Prefix

    # TLS 미사용: tls 블록 완전히 제거
    # tls:
    #   - secretName: (사용 안 함)
    #     hosts:
    #       - argorollouts.dokjongban.com

